#!/usr/bin/env bash
# setup-ipvlan-squid.sh
# Idempotent setup: ipvlan interfaces + squid config + hairpin routing
# Run after every reboot: sudo ./setup-ipvlan-squid.sh
#
# Safe to run multiple times - cleans up and recreates everything

set -euo pipefail

PHYS_IF="eno1"
IPVLAN_PREFIX="ipvlan"
MACV_PREFIX="macv"
COUNT=23
SQUID_CONF="/etc/squid/squid.conf"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info() { echo -e "${GREEN}[+] $1${NC}"; }
warn() { echo -e "${YELLOW}[!] $1${NC}"; }
die() { echo -e "${RED}[ERROR] $1${NC}" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "Run as root: sudo $0"

echo ""
info "=== IPvlan + Squid Setup (idempotent) ==="
echo ""

# --- Step 1: Clean up existing interfaces ---
info "Step 1: Cleaning up existing interfaces..."

for ((i=1; i<=COUNT; i++)); do
    for prefix in "$MACV_PREFIX" "$IPVLAN_PREFIX"; do
        ifname="${prefix}${i}"
        if ip link show "$ifname" &>/dev/null; then
            ip link del "$ifname" 2>/dev/null || true
        fi
    done
done
sleep 1

# --- Step 2: Create ipvlan interfaces ---
info "Step 2: Creating $COUNT ipvlan interfaces..."

for ((i=1; i<=COUNT; i++)); do
    ifname="${IPVLAN_PREFIX}${i}"
    ip link add link "$PHYS_IF" name "$ifname" type ipvlan mode l2
    ip link set "$ifname" up
done
sleep 1

# --- Step 3: Scan and assign static IPs ---
info "Step 3: Scanning for available IPs (arp-scan)..."

BASE_IP="192.168.1"
declare -a AVAILABLE_IPS
declare -A USED_IPS

# Use arp-scan to find all active hosts (fast, reliable)
while IFS=$'\t' read -r ip mac vendor; do
    # Extract just the last octet
    octet="${ip##*.}"
    USED_IPS["$octet"]=1
done < <(arp-scan --interface="$PHYS_IF" "${BASE_IP}.0/24" 2>/dev/null | grep -E "^${BASE_IP}\.[0-9]+")

info "Found ${#USED_IPS[@]} active hosts on network"

# Find available IPs (100-199 range, skip .200 for nginx)
for octet in {100..199}; do
    [[ $octet -eq 200 ]] && continue
    if [[ -z "${USED_IPS[$octet]:-}" ]]; then
        AVAILABLE_IPS+=("$octet")
        ((${#AVAILABLE_IPS[@]} >= COUNT)) && break
    fi
done

if ((${#AVAILABLE_IPS[@]} < COUNT)); then
    die "Only found ${#AVAILABLE_IPS[@]} available IPs, need $COUNT"
fi

info "Selected ${#AVAILABLE_IPS[@]} available IPs, assigning..."

declare -a ASSIGNED_IPS
for ((i=1; i<=COUNT; i++)); do
    ifname="${IPVLAN_PREFIX}${i}"
    octet="${AVAILABLE_IPS[$((i-1))]}"
    ip_addr="${BASE_IP}.${octet}"
    
    ip addr add "${ip_addr}/24" dev "$ifname" 2>/dev/null || true
    ASSIGNED_IPS+=("$ip_addr")
    echo "  $ifname -> $ip_addr"
done

# --- Step 4: Enable hairpin routing ---
info "Step 4: Enabling hairpin routing..."

sysctl -q -w net.ipv4.conf."$PHYS_IF".proxy_arp=1
sysctl -q -w net.ipv4.conf.all.route_localnet=1
sysctl -q -w net.ipv4.conf."$PHYS_IF".rp_filter=0
sysctl -q -w net.ipv4.conf.all.rp_filter=0

# Route to nginx container via gateway (hairpin through router)
NGINX_IP="${NGINX_IP:-192.168.1.200}"
GATEWAY="${GATEWAY:-192.168.1.1}"
ip route del "${NGINX_IP}/32" 2>/dev/null || true
ip route add "${NGINX_IP}/32" via "$GATEWAY" dev "$PHYS_IF"
info "Added hairpin route: $NGINX_IP via $GATEWAY"

# --- Step 5: Generate squid config ---
info "Step 5: Generating squid config..."

cat > "$SQUID_CONF" << 'HEADER'
# /etc/squid/squid.conf
# Auto-generated by setup-ipvlan-squid.sh
visible_hostname squid-multi-ip
HEADER

for ((i=1; i<=COUNT; i++)); do
    echo "http_port $((40000 + i)) name=proxy$i" >> "$SQUID_CONF"
done

cat >> "$SQUID_CONF" << 'ACLS'

acl SSL_ports port 443
acl Safe_ports port 80
acl Safe_ports port 443
acl Safe_ports port 1025-65535
acl CONNECT method CONNECT

http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports

acl localhost src 127.0.0.1/8 ::1
acl localnet src 192.168.1.0/24

http_access allow localhost
http_access allow localnet

ACLS

for ((i=1; i<=COUNT; i++)); do
    printf "acl via_proxy%-2d myportname proxy%d\n" "$i" "$i" >> "$SQUID_CONF"
done

echo "" >> "$SQUID_CONF"

for ((i=1; i<=COUNT; i++)); do
    echo "http_access allow via_proxy$i" >> "$SQUID_CONF"
done

cat >> "$SQUID_CONF" << 'MIDDLE'

http_access deny all

MIDDLE

for ((i=1; i<=COUNT; i++)); do
    printf "tcp_outgoing_address %-15s via_proxy%d\n" "${ASSIGNED_IPS[$((i-1))]}" "$i" >> "$SQUID_CONF"
done

cat >> "$SQUID_CONF" << 'FOOTER'

access_log daemon:/var/log/squid/access.log squid
cache_log /var/log/squid/cache.log
cache_store_log none
pid_filename /var/run/squid.pid
cache deny all
FOOTER

# --- Step 6: Restart squid ---
info "Step 6: Restarting squid..."
systemctl restart squid

# --- Done ---
echo ""
info "=== Setup Complete ==="
echo ""
echo "IPvlan interfaces: $COUNT"
echo "Squid ports: 40001-$((40000 + COUNT))"
echo "IP range: ${ASSIGNED_IPS[0]} - ${ASSIGNED_IPS[$((COUNT-1))]}"
echo ""
echo "Test: curl -sx http://127.0.0.1:40001 -k https://wp-lab | head -3"
echo ""
