#!/usr/bin/env bash
# setup-squid-macvlans.sh
# Creates macvlan interfaces and updates squid config with their IPs
#
# Usage: sudo ./setup-squid-macvlans.sh

set -euo pipefail

PHYS_IF="eno1"
MACV_PREFIX="macv"
COUNT=23
SQUID_CONF="/etc/squid/squid.conf"
SQUID_CONF_BACKUP="/etc/squid/squid.conf.bak.$(date +%Y%m%d-%H%M%S)"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

die() { echo -e "${RED}Error: $1${NC}" >&2; exit 1; }
info() { echo -e "${GREEN}$1${NC}"; }
warn() { echo -e "${YELLOW}$1${NC}"; }

[[ $EUID -eq 0 ]] || die "Run as root (sudo)"

# Step 1: Create macvlan interfaces
info "=== Step 1: Creating $COUNT macvlan interfaces ==="

for ((i=1; i<=COUNT; i++)); do
    ifname="${MACV_PREFIX}${i}"
    
    if ip link show "$ifname" &>/dev/null; then
        warn "Interface $ifname already exists - skipping creation"
    else
        info "Creating macvlan: $ifname"
        ip link add "$ifname" link "$PHYS_IF" type macvlan mode bridge
        ip link set "$ifname" up
    fi
done

# Step 2: Request DHCP leases
info "=== Step 2: Requesting DHCP leases ==="

for ((i=1; i<=COUNT; i++)); do
    ifname="${MACV_PREFIX}${i}"
    
    # Check if already has an IP
    if ip -4 addr show "$ifname" 2>/dev/null | grep -q "inet "; then
        warn "$ifname already has IP - skipping DHCP"
    else
        info "Requesting DHCP on $ifname..."
        dhclient -1 "$ifname" 2>/dev/null || warn "DHCP on $ifname may have failed"
    fi
done

# Give DHCP a moment to settle
sleep 2

# Step 3: Collect IPs
info "=== Step 3: Collecting assigned IPs ==="

declare -a IPS
for ((i=1; i<=COUNT; i++)); do
    ifname="${MACV_PREFIX}${i}"
    ip=$(ip -4 addr show "$ifname" 2>/dev/null | grep -oP 'inet \K[\d.]+' | head -1)
    
    if [[ -z "$ip" ]]; then
        warn "$ifname has no IP - will use placeholder"
        ip="0.0.0.0"
    else
        info "$ifname -> $ip"
    fi
    
    IPS+=("$ip")
done

# Step 4: Generate squid config
info "=== Step 4: Generating squid config ==="

# Backup existing config
if [[ -f "$SQUID_CONF" ]]; then
    cp "$SQUID_CONF" "$SQUID_CONF_BACKUP"
    info "Backed up existing config to $SQUID_CONF_BACKUP"
fi

cat > "$SQUID_CONF" << 'SQUID_HEADER'
# /etc/squid/squid.conf
# Auto-generated multi-IP egress proxy config
# Generated by setup-squid-macvlans.sh

# ===== Basic Settings =====
visible_hostname squid-multi-ip
SQUID_HEADER

# Add http_port lines
for ((i=1; i<=COUNT; i++)); do
    port=$((40000 + i))
    echo "http_port $port name=proxy$i" >> "$SQUID_CONF"
done

cat >> "$SQUID_CONF" << 'SQUID_ACLS'

# ===== Safe ports and CONNECT handling =====
acl SSL_ports port 443
acl Safe_ports port 80
acl Safe_ports port 443
acl Safe_ports port 1025-65535
acl CONNECT method CONNECT

http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports

# ===== Access control =====
acl localhost src 127.0.0.1/8 ::1
acl localnet src 192.168.1.0/24

http_access allow localhost
http_access allow localnet

# ===== Per-port ACLs =====
SQUID_ACLS

# Add per-port ACLs
for ((i=1; i<=COUNT; i++)); do
    printf "acl via_proxy%-2d myportname proxy%d\n" "$i" "$i" >> "$SQUID_CONF"
done

echo "" >> "$SQUID_CONF"

# Add http_access allow rules
for ((i=1; i<=COUNT; i++)); do
    echo "http_access allow via_proxy$i" >> "$SQUID_CONF"
done

cat >> "$SQUID_CONF" << 'SQUID_DENY'

# Deny everything else
http_access deny all

# ===== Outgoing source IP binding =====
SQUID_DENY

# Add tcp_outgoing_address lines
for ((i=1; i<=COUNT; i++)); do
    printf "tcp_outgoing_address %-15s via_proxy%d\n" "${IPS[$((i-1))]}" "$i" >> "$SQUID_CONF"
done

cat >> "$SQUID_CONF" << 'SQUID_FOOTER'

# ===== Logging =====
access_log daemon:/var/log/squid/access.log squid
cache_log /var/log/squid/cache.log
cache_store_log none
pid_filename /var/run/squid.pid

# ===== Cache (disabled) =====
cache deny all

# ===== End of config =====
SQUID_FOOTER

info "=== Step 5: Restarting squid ==="
systemctl restart squid && info "Squid restarted successfully" || warn "Squid restart failed - check config"

# Summary
echo ""
info "=== Summary ==="
echo "Macvlan interfaces: $COUNT"
echo "Squid ports: 40001-$((40000 + COUNT))"
echo "Config written to: $SQUID_CONF"
echo ""
echo "Interface -> IP mapping:"
for ((i=1; i<=COUNT; i++)); do
    printf "  macv%-2d (port %d) -> %s\n" "$i" "$((40000 + i))" "${IPS[$((i-1))]}"
done
